In [144]:
import pandas as pd

In [145]:
import matplotlib.pyplot as plt

In [146]:
df_gols = pd.read_csv("campeonato-brasileiro-gols.csv")

In [147]:
df_gols = pd.DataFrame(df_gols)

In [148]:
df_gols.columns

Index(['partida_id', 'rodada', 'clube', 'atleta', 'minuto', 'tipo_de_gol'], dtype='object')

In [149]:
df_gols["minuto"]

0       59
1       45
2       31
3        6
4       63
        ..
8927    58
8928    26
8929    82
8930    63
8931    29
Name: minuto, Length: 8932, dtype: object

In [150]:
df_gols["minuto"].value_counts()

minuto
59       117
71       117
90+3     117
84       116
88       114
        ...
90+13      2
90+12      2
0          1
45+10      1
45+11      1
Name: count, Length: 116, dtype: int64

In [151]:
df_gols["minuto"].describe()

count     8932
unique     116
top         59
freq       117
Name: minuto, dtype: object

In [152]:
df_gols["minuto"] = pd.to_numeric(df_gols["minuto"], errors='coerce')

In [153]:
above_74 = df_gols[df_gols["minuto"] > 74]

In [154]:
#above_74.plot(kind='bar')

In [155]:
above_74

,partida_id,rodada,clube,atleta,minuto,tipo_de_gol
5,4612,1,Cruzeiro,Marcelo Moreno,90.0,NaN
6,4612,1,Bahia,Anderson Talisca,80.0,Penalty
11,4615,1,Santos,Gabriel Barbosa,80.0,NaN
14,4616,1,Palmeiras,Leandro,83.0,NaN
15,4616,1,Palmeiras,Alan Kardec,88.0,NaN
...,...,...,...,...,...,...
8898,8393,37,Bragantino,Léo Ortiz,75.0,NaN
8900,8395,37,Athletico-PR,Madson,75.0,NaN
8914,8399,38,Fluminense,John Kennedy,81.0,NaN
8915,8400,38,Cruzeiro,Nikão,80.0,NaN
8929,8405,38,Vasco,Sergio Antonio De Luiz Junior,82.0,NaN

In [156]:
above_74.columns

Index(['partida_id', 'rodada', 'clube', 'atleta', 'minuto', 'tipo_de_gol'], dtype='object')

In [157]:
above_74.index

Index([   5,    6,   11,   14,   15,   19,   20,   24,   28,   34,
       ...
       8866, 8870, 8877, 8886, 8889, 8898, 8900, 8914, 8915, 8929],
      dtype='int64', length=1594)

In [158]:

above_74.reset_index(drop=True, inplace=True)
above_74

,partida_id,rodada,clube,atleta,minuto,tipo_de_gol
0,4612,1,Cruzeiro,Marcelo Moreno,90.0,NaN
1,4612,1,Bahia,Anderson Talisca,80.0,Penalty
2,4615,1,Santos,Gabriel Barbosa,80.0,NaN
3,4616,1,Palmeiras,Leandro,83.0,NaN
4,4616,1,Palmeiras,Alan Kardec,88.0,NaN
...,...,...,...,...,...,...
1589,8393,37,Bragantino,Léo Ortiz,75.0,NaN
1590,8395,37,Athletico-PR,Madson,75.0,NaN
1591,8399,38,Fluminense,John Kennedy,81.0,NaN
1592,8400,38,Cruzeiro,Nikão,80.0,NaN
1593,8405,38,Vasco,Sergio Antonio De Luiz Junior,82.0,NaN